### ISSUE TITLE
Prototype definition for DRA818::setFilters does not match and won't compile

### ISSUE THREAD

**Issue by dfannin** [darksidelemm/dra818#1]
The prototype definition for DRA818::setFilters in the .h file is:
        void setFilters(uint8_t  preemph, uint8_t highpass, uint8_t lowpass);

However, in the .cpp file , the definition is:
void DRA818::setFilters(boolean preemph, boolean highpass, boolean lowpass)

So the library won't compile.

I assume you should change all the parameters to boolean

**Comment by mrmabs** [comment]
I've fixed the issue in my fork and have submitted the pull request

**Comment by darksidelemm** [comment]
Thanks for the fix, I haven't been paying much attention to this repository for a looong while...
